"""initial schema

Revision ID: 435ce62fbbbb
Revises: 
Create Date: 2026-03-26 19:18:28.714956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435ce62fbbbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_entries_user_id'), 'credit_entries', ['user_id'], unique=False)
    op.create_table('model_routing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_tier', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('gpu_type', sa.String(length=50), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('vllm_args', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_tier')
    )
    op.create_table('simulation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('seed_text', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONING', 'RUNNING', 'COMPLETED', 'FAILED', 'REFUNDED', name='jobstatus'), nullable=False),
    sa.Column('pipeline_stage', sa.Integer(), nullable=True),
    sa.Column('result_report', sa.Text(), nullable=True),
    sa.Column('result_chat_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gpu_provider', sa.String(length=50), nullable=True),
    sa.Column('gpu_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_user_id'), 'simulation_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_jobs_user_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_table('model_routing')
    op.drop_index(op.f('ix_credit_entries_user_id'), table_name='credit_entries')
    op.drop_table('credit_entries')
    # ### end Alembic commands ###
