<template>
  <div class="min-h-screen bg-ocean-midnight text-mist-foam">
    <!-- Toolbar -->
    <ResultsToolbar
      :title="job?.goal || 'Results'"
      :viewMode="viewMode"
      :showToggle="true"
      :showData="simDataAvailable"
      @update:viewMode="viewMode = $event"
    />

    <!-- Loading -->
    <div v-if="loading" class="flex items-center justify-center" style="height: calc(100vh - 140px)">
      <div class="text-mist-slate text-sm">Loading results…</div>
    </div>

    <!-- Not found -->
    <div v-else-if="!job" class="flex items-center justify-center" style="height: calc(100vh - 140px)">
      <div class="text-mist-slate text-sm">Results not found.</div>
    </div>

    <template v-else>
      <!-- ── Story View ── -->
      <div v-if="viewMode === 'story'" class="relative pt-[120px] pb-24">
        <ReportToc :items="storySections" />

        <div class="max-w-[820px] mx-auto px-6 space-y-6">
          <!-- Meta row -->
          <div id="story-meta" class="flex items-center gap-3 font-mono text-[10px] text-mist-slate uppercase tracking-wider">
            <span>Simulation</span>
            <span class="w-1 h-1 rounded-full bg-mist-depth"></span>
            <span>{{ simScale.participants ?? '—' }} participants</span>
            <span class="w-1 h-1 rounded-full bg-mist-depth"></span>
            <span>{{ simScale.horizon_days ?? '—' }}d horizon</span>
            <span v-if="job.tier" class="w-1 h-1 rounded-full bg-mist-depth"></span>
            <span v-if="job.tier" class="capitalize">{{ job.tier }} depth</span>
          </div>

          <!-- Q+A Hero -->
          <div id="story-hero" data-reveal>
            <QuestionAnswerHero
              :question="job.goal"
              :verdict="verdict"
              :stakeholder-positions="stakeholderPositions"
            />
          </div>

          <!-- What the simulation surfaced -->
          <div v-if="structured?.findings?.length" id="story-findings">
            <div class="font-mono text-[10px] text-mist-slate uppercase tracking-wider mb-4 pl-1">What the simulation surfaced</div>
            <div :class="findingsGridClass">
              <FindingSlotCard
                v-for="(f, i) in structured.findings"
                :key="i"
                :slot-name="f.slot"
                :title="f.title"
                :body="f.body"
                :citation="f.citation"
              />
            </div>
          </div>

          <!-- Sim-scale footer -->
          <SimScaleFooter id="story-scale" :scale="simScale" />

          <!-- Share bar -->
          <div class="flex items-center justify-between px-5 py-4 bg-ocean-deep/40 border border-mist-depth rounded-xl">
            <div class="text-xs text-mist-drift">
              This artifact was generated by a multi-agent simulation. Open the Report for methodology and source citations.
            </div>
            <div class="flex gap-2">
              <button class="text-xs px-3.5 py-2 rounded-lg border border-mist-depth text-mist hover:border-ocean-glow hover:text-mist-foam transition"
                      @click="handleShare">Copy link</button>
              <button class="text-xs px-3.5 py-2 rounded-lg border border-ocean-glow text-ocean-glow bg-ocean-glow/10 hover:text-mist-foam transition"
                      :disabled="pdfLoading" @click="handleExport">
                {{ pdfLoading ? 'Exporting…' : 'Export PDF' }}
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- ── Graph View ── -->
      <div v-else-if="viewMode === 'graph'" class="pt-[52px] overflow-hidden" style="height: 100vh">
        <GraphVisualization
          ref="graphVizRef"
          :nodes="graphData?.nodes || []"
          :edges="graphData?.edges || []"
          :metadata="graphData?.metadata || {}"
          :chat-log="chatLog"
          :loading="graphLoading"
          :error="graphError"
          @node-selected="onNodeSelected"
        />
      </div>

      <!-- ── Data View ── -->
      <div v-else-if="viewMode === 'data'" class="pt-[120px] overflow-hidden" style="min-height: calc(100vh - 140px)">
        <DataDashboard :jobId="jobId" />
      </div>

      <!-- ── Report View ── -->
      <div v-else-if="viewMode === 'report'" class="relative pt-[120px] pb-24">
        <ReportToc :items="tocItems" />

        <div class="max-w-[800px] mx-auto pl-12 pr-4 xl:pl-16 space-y-12">
          <div id="report-header" data-reveal class="bg-ocean-deep border border-mist-depth rounded-2xl p-8">
            <h1 class="text-2xl font-bold text-mist-foam mb-2">{{ job.goal }}</h1>
            <p class="text-sm text-mist-slate capitalize">
              {{ job.tier }} tier
              <span v-if="job.created_at"> &bull; Started {{ formatDate(job.created_at) }}</span>
              <span v-if="job.completed_at"> &bull; Completed {{ formatDate(job.completed_at) }}</span>
            </p>
          </div>

          <div id="report-content" data-reveal class="bg-ocean-deep border border-mist-depth rounded-2xl p-10">
            <ReportViewer :content="job.result_report || job.report || 'No report available.'" />
          </div>

          <div v-if="chatMessages.length > 0" id="report-chat">
            <ChatReplay :messages="chatMessages" />
          </div>
        </div>
      </div>
    </template>

    <!-- Bottom bar -->
    <ResultsBottomBar
      v-if="job"
      :showPng="viewMode === 'graph'"
      :showJson="viewMode !== 'graph'"
      :showCsv="viewMode !== 'graph'"
      :pdfLoading="pdfLoading"
      :shareStatus="shareStatus"
      @export="handleExport"
      @share="handleShare"
    />
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useRoute } from 'vue-router'
import ReportViewer from '../components/ReportViewer.vue'
import ChatReplay from '../components/ChatReplay.vue'
import GraphVisualization from '../components/graph/GraphVisualization.vue'
import ResultsToolbar from '../components/results/ResultsToolbar.vue'
import ResultsBottomBar from '../components/results/ResultsBottomBar.vue'
import ReportToc from '../components/results/ReportToc.vue'
import QuestionAnswerHero from '../components/results/QuestionAnswerHero.vue'
import FindingSlotCard from '../components/results/FindingSlotCard.vue'
import SimScaleFooter from '../components/results/SimScaleFooter.vue'
import { useScrollReveal } from '../composables/useScrollReveal.js'
import { useSimulationData } from '../composables/useSimulationData.js'
import { useResultsExport } from '../composables/useResultsExport.js'
import { getJob, getJobGraph } from '../api/jobs.js'
import DataDashboard from '../components/data/DataDashboard.vue'

const route = useRoute()
const jobId = route.params.id

useScrollReveal()

const job = ref(null)
const loading = ref(true)
const viewMode = ref('story')

const graphVizRef = ref(null)
const graphData = ref(null)
const graphLoading = ref(false)
const graphError = ref(null)
const hasGraph = ref(false)

const simDataAvailable = ref(false)

const isSmallScreen = ref(window.innerWidth < 768)

// ── Computed ──────────────────────────────────────────────────────────────────

const {
  chatLog,
  chatMessages,
  structured,
  verdict,
  stakeholderPositions,
  namedCoalitions,
  phaseBoundaries,
  quotablePosts,
  simScale,
  buildNodeRelationships,
} = useSimulationData(job)
const { pdfLoading, shareStatus, handleExport, handleShare } = useResultsExport(jobId, job, chatMessages, graphVizRef)

const storySections = computed(() => [
  { id: 'story-hero', label: 'Question & answer' },
  { id: 'story-findings', label: 'Findings' },
  { id: 'story-scale', label: 'Scale' },
])

const findingsGridClass = computed(() => {
  const n = structured.value?.findings?.length ?? 0
  if (n <= 1) return 'grid gap-4 grid-cols-1'
  if (n === 2) return 'grid gap-4 grid-cols-1 md:grid-cols-2'
  if (n === 3) return 'grid gap-4 grid-cols-1 md:grid-cols-2 [&>*:nth-child(3)]:md:col-span-2'
  return 'grid gap-4 grid-cols-1 md:grid-cols-2'  // 4+ → 2x2
})

const tocItems = computed(() => {
  const items = [
    { id: 'report-header', label: 'Overview' },
    { id: 'report-content', label: 'Report' },
  ]
  if (chatMessages.value.length > 0) items.push({ id: 'report-chat', label: 'Conversation' })
  return items
})

// ── Data fetching ─────────────────────────────────────────────────────────────

async function fetchGraphData() {
  graphLoading.value = true
  graphError.value = null
  try {
    const raw = await getJobGraph(jobId)
    if (raw?.nodes?.length && raw?.edges?.length) {
      raw.nodes = buildNodeRelationships(raw.nodes, raw.edges)
    }
    graphData.value = raw
    hasGraph.value = graphData.value?.nodes?.length > 0
  } catch (err) {
    graphError.value = err.response?.status === 404
      ? 'Graph data not available for this simulation.'
      : 'Failed to load graph data.'
    hasGraph.value = false
  } finally {
    graphLoading.value = false
  }
}

function onNodeSelected(_entityName) {
  // In three-view mode there's no split pane; graph view is fullscreen.
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────

function onResize() {
  isSmallScreen.value = window.innerWidth < 768
}

onMounted(async () => {
  window.addEventListener('resize', onResize)
  try {
    job.value = await getJob(jobId)
    await fetchGraphData()

    simDataAvailable.value = job.value?.sim_data_available || false
  } catch (err) {
    console.error('Failed to load results:', err)
  } finally {
    loading.value = false
  }
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', onResize)
})

function formatDate(dateStr) {
  if (!dateStr) return ''
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  })
}
</script>
